# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tlfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.cache/wt} [current_project]
set_property parent.project_path {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/stddef.h}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Bus/bus.h}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/global_config.h}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/nettype.h}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/rom.h}
}
set_property file_type "Verilog Header" [get_files {{D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/stddef.h}}]
set_property file_type "Verilog Header" [get_files {{D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Bus/bus.h}}]
set_property file_type "Verilog Header" [get_files {{D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/global_config.h}}]
set_property file_type "Verilog Header" [get_files {{D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/Global_Headers/nettype.h}}]
set_property file_type "Verilog Header" [get_files {{D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/rom.h}}]
read_verilog -library xil_defaultlib {
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/bus.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/bus_addr_dec.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/bus_arbiter.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/bus_master_mux.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/bus_slave_mux.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/rom.v}
  {D:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/new/chip_top.v}
}
read_ip -quiet {{d:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Users/leezi/Documents/EE Projects/Vivado/AZ_Processor/AZ_Processor.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top chip_top -part xc7a35tlfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chip_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chip_top_utilization_synth.rpt -pb chip_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
